#!/bin/bash -e

MACNUMBER=$(
    ip l | \
    sed -n -e '/ether/s/.*\(..\):\(..\):\(..\):\(..\):\(..\):\(..\).*brd.*/\1\2\3\4\5\6/p' | \
    head -n 1
)

NEWNAME=$(
    tr -cd A-Za-z0-9 </sys/devices/virtual/dmi/id/chassis_asset_tag | grep . || echo jts$MACNUMBER
)

logger -s "Setting hostname to $NEWNAME"

echo "$NEWNAME" > /etc/hostname
sed -i -f - /etc/hosts <<EOF
1{
i # this content comes from the ${DPKG_MAINTSCRIPT_PACKAGE} package
i 127.0.1.1 $NEWNAME
i # end of content from the ${DPKG_MAINTSCRIPT_PACKAGE} package
}
/127\.0\.1\.1/d
/${DPKG_MAINTSCRIPT_PACKAGE}.*package/d
EOF
