#!/bin/bash -e
date +"UPGRADE START %x %X"
apt-get -q update
export DEBIAN_FRONTEND=noninteractive
yes '' | apt-get -q -y -o Dpkg::Options::='--force-confdef' -o Dpkg::Options::='--force-confold' dist-upgrade
date +"UPGRADE OK %x %X in $SECONDS seconds"
